### PR TITLE
Draft PR: Support for IDA 9.0 API Changes

### PR DESCRIPTION
**Pull request by xuing**
This  **Draft**  PR updates the script to work with IDA 9.0. The changes ensure compatibility with IDA 9.0.

**Compatibility with older versions is untested.**

### CODE REVIEW

**Comment by Fi5t** [comment]
Unfortunately it doesn't work. I got an error:
```
/tmp/out/ida_script/addNames.py: module 'idc' has no attribute 'get_struc'
Traceback (most recent call last):
  File "/.../python/ida_idaapi.py", line 501, in IDAPython_ExecScript
    exec(code, g)
    ~~~~^^^^^^^^^
  File "/tmp/out/ida_script/addNames.py", line 31127, in <module>
    thrs, pps = create_Dart_structs()
                ~~~~~~~~~~~~~~~~~~~^^
  File "/tmp/out/ida_script/addNames.py", line 16409, in create_Dart_structs
    struc = idc.get_struc(sid2)
            ^^^^^^^^^^^^^
  File "/.../python/ida_ida.py", line 2907, in __getattribute__
    return getattr(self.orig, name)
AttributeError: module 'idc' has no attribute 'get_struc'
```

IDA version: `9.1.250226`

**Comment by ZERO-A-ONE** [comment]
> Unfortunately it doesn't work. I got an error:
> 
> ```
> /tmp/out/ida_script/addNames.py: module 'idc' has no attribute 'get_struc'
> Traceback (most recent call last):
>   File "/.../python/ida_idaapi.py", line 501, in IDAPython_ExecScript
>     exec(code, g)
>     ~~~~^^^^^^^^^
>   File "/tmp/out/ida_script/addNames.py", line 31127, in <module>
>     thrs, pps = create_Dart_structs()
>                 ~~~~~~~~~~~~~~~~~~~^^
>   File "/tmp/out/ida_script/addNames.py", line 16409, in create_Dart_structs
>     struc = idc.get_struc(sid2)
>             ^^^^^^^^^^^^^
>   File "/.../python/ida_ida.py", line 2907, in __getattribute__
>     return getattr(self.orig, name)
> AttributeError: module 'idc' has no attribute 'get_struc'
> ```
> 
> IDA version: `9.1.250226`

I have provided a new patch. The generated script does not produce any errors on my 9.0 RC1. Could you help me check whether it works properly on 9.1?
